apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: mysql-local-storage
  resources:
    requests:
      storage: 10Mi